<script src="{{URL('public/thm/js/jquery.js')}}"></script>
<script src="{{URL('public/thm/js/popper.min.js')}}"></script>
<script src="{{URL('public/thm/js/bootstrap.min.js')}}"></script>
<!--Revolution Slider-->
<script src="{{URL('public/thm/plugins/revolution/js/jquery.themepunch.revolution.min.js')}}"></script>
<script src="{{URL('public/thm/plugins/revolution/js/jquery.themepunch.tools.min.js')}}"></script>
<script src="{{URL('public/thm/plugins/revolution/js/extensions/revolution.extension.actions.min.js')}}"></script>
<script src="{{URL('public/thm/plugins/revolution/js/extensions/revolution.extension.carousel.min.js')}}"></script>
<script src="{{URL('public/thm/plugins/revolution/js/extensions/revolution.extension.kenburn.min.js')}}"></script>
<script src="{{URL('public/thm/plugins/revolution/js/extensions/revolution.extension.layeranimation.min.js')}}"></script>
<script src="{{URL('public/thm/plugins/revolution/js/extensions/revolution.extension.migration.min.js')}}"></script>
<script src="{{URL('public/thm/plugins/revolution/js/extensions/revolution.extension.navigation.min.js')}}"></script>
<script src="{{URL('public/thm/plugins/revolution/js/extensions/revolution.extension.parallax.min.js')}}"></script>
<script src="{{URL('public/thm/plugins/revolution/js/extensions/revolution.extension.slideanims.min.js')}}"></script>
<script src="{{URL('public/thm/js/plugins/revolution/js/extensions/revolution.extension.video.min.js')}}"></script>
<script src="{{URL('public/thm/js/main-slider-script.js')}}"></script>
<!--Revolution Slider-->

<script src="{{URL('public/thm/js/jquery-ui.js')}}"></script>
<script src="{{URL('public/thm/js/jquery.fancybox.js')}}"></script>
<script src="{{URL('public/thm/js/owl.js')}}"></script>
<script src="{{URL('public/thm/js/wow.js')}}"></script>
<script src="{{URL('public/thm/js/appear.js')}}"></script>
<script src="{{URL('public/thm/js/script.js')}}"></script>